export enum ErrorCode {
  NETWORK_UNAVAILABLE = "NETWORK_UNAVAILABLE",
  INVALID_INPUT = "INVALID_INPUT",
  EXECUTION_DENIED = "EXECUTION_DENIED",
  RISK_LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED",
  CONTRACT_MISMATCH = "CONTRACT_MISMATCH",
  UNAUTHORIZED_SIGNER = "UNAUTHORIZED_SIGNER",
}
